[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-sdk'

dependencies {
  api project(':core')
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  testImplementation 'junit:junit:4.13.2'
}

jar {
  archiveFileName.set("${appName}-sdk-${projectVersion}.jar")
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
